### ISSUE TITLE
Plot 48-well plate Data

### ISSUE THREAD

**Issue by Ischlem** [firasmidani/amiga#21]
I would like to plote data from 48-well plates, however I get an error message that only data for 96-well plates can be plotted. Any way to enable 48-well data?

**Comment by firasmidani** [comment]
There is no way to plot 48-well data with `AMiGA`. However, if you use the [`--save-gp-data`](https://firasmidani.github.io/amiga/doc/command-line-interface.html) parameter with either the `fit` command, `AMiGA` will export the growth curves in a tidy format into a tab-delimited text file. You can import this text file into your software of choice (e.g. R or python) to plot the growth curves yourself.
