### ISSUE TITLE
Auc_empirical 

### ISSUE THREAD

**Issue by Edison2021** [firasmidani/amiga#4]
Hi Firas 
Thanks for your software that makes PM analysis easier. I wonder if AMiGA can give empirical AUC?

Best
Edison

**Comment by firasmidani** [comment]
The [`fit`](https://firasmidani.github.io/amiga/doc/fitting.html) function estimates the AUC after modelling a growth curve with Gaussian Process. However, neither the `summarize` or `fit` function computes the empirical AUC, i.e. before modelling a growth curve. Still, it should be an easy feature to add to the software and I will try to include it in the next update.

**Comment by Edison2021** [comment]
Thanks, hopefully it is coming soon!

Best
Edison

**Comment by firasmidani** [comment]
The `summarize` function will now automatically compute the empirical AUC. See column `OD_Emp_AUC` in the summary results table. The empirical AUC is computed without any modifications to the growth curve. If there are any issues with this new feature, please open a new issue. Thank you!

**Comment by Edison2021** [comment]
Hi Firas
Thanks for the updates.  Do I need to reinstall amiga for the function?

Best
Edison

**Comment by firasmidani** [comment]
Yes. If you installed with `git`, you can simply `git pull`. Otherwise, please re-download amiga and simply replace your old amiga folder with the new one.
